version: '3.9'

services:
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://admin:admin@mongo:27017/tuemorning_db

  product-service:
    build:
      context: ./product-service
    ports:
      - "3001:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://admin:admin@mongo:27017/tuemorning_db

  user-service:
    build:
      context: ./user-service
    ports:
      - "3002:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://admin:admin@mongo:27017/tuemorning_db
